### ISSUE TITLE
进入考勤的koisk 模式，选择员工报错。

### ISSUE THREAD

**Issue by niulinlnc** [suxuefeng20/odooDingDing#13]
进入考勤的koisk 模式，选择员工报错。
另外admin用户（未关联钉钉）进入钉钉仪表盘也会报同样的错误。
Uncaught TypeError: Cannot read property 'append' of undefined
http://192.168.31.93:8069/web/content/753-d3313a9/web.assets_backend.js:3359
Traceback:
TypeError: Cannot read property 'append' of undefined
    at Class.renderButtons (http://192.168.31.93:8069/web/content/753-d3313a9/web.assets_backend.js:3359:694)
    at Class.<anonymous> (http://192.168.31.93:8069/web/content/556-781c308/web.assets_common.js:3541:371)
    at Class.renderButtons (http://192.168.31.93:8069/web/content/753-d3313a9/web.assets_backend.js:3364:408)
    at Class.<anonymous> (http://192.168.31.93:8069/web/content/556-781c308/web.assets_common.js:3541:371)
    at Class.renderButtons (http://192.168.31.93:8069/web/content/753-d3313a9/web.assets_backend.js:3399:271)
    at Class.<anonymous> (http://192.168.31.93:8069/web/content/556-781c308/web.assets_common.js:3541:371)
    at Class.renderButtons (http://192.168.31.93:8069/web/content/753-d3313a9/web.assets_backend.js:3529:225)
    at Class.renderButtons (http://192.168.31.93:8069/web/content/556-781c308/web.assets_common.js:3541:371)
    at Class._renderControlPanelElements (http://192.168.31.93:8069/web/content/753-d3313a9/web.assets_backend.js:1294:175)
    at Class.start (http://192.168.31.93:8069/web/content/753-d3313a9/web.assets_backend.js:1286:1427)

**Comment by niulinlnc** [comment]
好像已修复
