### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by digitalliuzg** [suxuefeng20/odooDingDing#27]
odoo.tools.convert.ParseError: "External ID not found in the system: ali_dindin.dd_setting_group" while parsing file:/e:/odoo/source/suxuefeng/odoodingding/dindin_callback/views/call_back_list.xml:43, near
<menuitem name="&#x56DE;&#x8C03;&#x7BA1;&#x7406;" id="dindin_callbacke_main_menu" parent="ali_dindin.main_menu" sequence="50" groups="ali_dindin.dd_setting_group"/>

**Comment by niulinlnc** [comment]
安装callback之前先安装ali_dindin 模块了没？

**Comment by digitalliuzg** [comment]
odoo.tools.convert.ParseError: "External ID not found in the system: ali_dindin.dd_setting_group" while parsing file:/e:/source/suxuefeng/odoodingding/dindin_callback/views/call_back_list.xml:43, near
<menuitem name="&#x56DE;&#x8C03;&#x7BA1;&#x7406;" id="dindin_callbacke_main_menu" parent="ali_dindin.main_menu" sequence="50" groups="ali_dindin.dd_setting_group"/>

**Comment by digitalliuzg** [comment]
貌似安装上了，但运行时报错
![image](https://user-images.githubusercontent.com/11321237/59153271-1ab89300-8a88-11e9-8402-3debadb66672.png)

Odoo Server Error
Traceback (most recent call last):
  File "E:\odoo\odoo\api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 131

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\odoo\odoo\fields.py", line 975, in __get__
    value = record.env.cache.get(record, self)
  File "E:\odoo\odoo\api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.actions.act_window(131,).search_view', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\odoo\odoo\http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "E:\odoo\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "E:\odoo\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "E:\odoo\odoo\http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "E:\odoo\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "E:\odoo\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "E:\odoo\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "E:\odoo\odoo\http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "E:\odoo\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "e:\dvt\drissuite12_win_v1\odoo\odoo\addons\web\controllers\main.py", line 1261, in load
    action = request.env[action_type].browse([action_id]).read()
  File "e:\dvt\drissuite12_win_v1\odoo\odoo\addons\base\models\ir_actions.py", line 210, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "E:\odoo\odoo\models.py", line 2782, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "E:\odoo\odoo\models.py", line 5087, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "E:\odoo\odoo\fields.py", line 979, in __get__
    self.determine_value(record)
  File "E:\odoo\odoo\fields.py", line 1090, in determine_value
    self.compute_value(recs)
  File "E:\odoo\odoo\fields.py", line 1046, in compute_value
    self._compute_value(records)
  File "E:\odoo\odoo\fields.py", line 1037, in _compute_value
    getattr(records, self.compute)()
  File "e:\dvt\drissuite12_win_v1\odoo\odoo\addons\base\models\ir_actions.py", line 170, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "E:\odoo\odoo\api.py", line 821, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "E:\odoo\odoo\modules\registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'dindin.approval.template'

**Comment by digitalliuzg** [comment]
安装审批模板模块，问题解决。

**Comment by digitalliuzg** [comment]
安装日志报错：
raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: <class 'odoo.tools.convert.ParseError'>: "External ID not found in the system: ali_dindin.dingding_main_groups
<record id="dd_get_report_templategroup" model="res.groups">
        <field name="name">允许拉取钉钉日志模板</field>
        <field name="category_id" ref="ali_dindin.dingding_main_groups"/>
        <field name="users" eval="[             (4, ref('base.user_admin'))   ]"/>
    </record>
file:/e:/dvt/drissuite12_win_v1/source/suxuefeng/odoodingding/dindin_report/security/dindin_security.xml
4" while evaluating
'records.button_immediate_install()'

**Comment by digitalliuzg** [comment]
安装“钉钉办公-扫码/免密登录模块”报错
File "e:\odoo\source\suxuefeng\odoodingding\dindin_login\models\__init__.py", line 3, in <module>
    from . import res_users
  File "e:\odoo\source\suxuefeng\odoodingding\dindin_login\models\res_users.py", line 5, in <module>
    import pypinyin
ValueError: <class 'ImportError'>: "No module named 'pypinyin'" while evaluating
'records.button_immediate_install()'

**Comment by digitalliuzg** [comment]
安装“钉钉办公-回调管理"报错：
   raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: <class 'odoo.tools.convert.ParseError'>: "External ID not found in the system: ali_dindin.dd_setting_group
<menuitem name="&#x56DE;&#x8C03;&#x7BA1;&#x7406;" id="dindin_callbacke_main_menu" parent="ali_dindin.main_menu" sequence="50" groups="ali_dindin.dd_setting_group"/>
file:/e:/odoo/source/suxuefeng/odoodingding/dindin_callback/views/call_back_list.xml
43" while evaluating
'records.button_immediate_install()'

**Comment by digitalliuzg** [comment]
安装“钉钉办公-考勤排班详情"报错：
ValueError: <class 'odoo.tools.convert.ParseError'>: "External ID not found in the system: ali_dindin.dingding_main_groups
<record id="dd_attendance_groups_group" model="res.groups">
        <field name="name">操作钉钉考勤组</field>
        <field name="category_id" ref="ali_dindin.dingding_main_groups"/>
        <field name="users" eval="[             (4, ref('base.user_admin'))   ]"/>
    </record>
file:/e:/odoo/source/suxuefeng/odoodingding/dindin_attendance/security/dingding_security.xml
4" while evaluating
'records.button_immediate_install()'

**Comment by niulinlnc** [comment]
你的安装有问题，正常情况下，安装了ali_dindin这个模块后，其他大部分模块自动安装好了。

**Comment by digitalliuzg** [comment]
我是空库安装模块报的错，用的是最12的代码.

**Comment by digitalliuzg** [comment]
我是用12社区版空库安装的，dindio 12版报的错。

**Comment by niulinlnc** [comment]
现在最新的代码都在master分支，12分支可能会有点延后。
